import { User } from '../../../models/class';

export const users: User[] = [
  {
    id: 1,
    fullName: 'John Doe',
    email: 'john@example.com',
    username: 'johndoe',
    password: 'Password123!',
    mobilePhone: '08123456701',
    status: 'Active',
    branch: 'Lagos',
    superUser: false,
    address: '123 Allen Ave, Ikeja, Lagos',
    roles: 'Admin',
    profilePicture: 'https://example.com/profiles/john.jpg',
  },
  {
    id: 2,
    fullName: 'Jane Smith',
    email: 'jane@example.com',
    username: 'janesmith',
    password: 'SecurePass456!',
    mobilePhone: '08098765432',
    status: 'Inactive',
    branch: 'Abuja',
    superUser: true,
    address: 'Plot 24, Gwarinpa, Abuja',
    roles: 'Manager',
    profilePicture: 'https://example.com/profiles/jane.jpg',
  },
  {
    id: 3,
    fullName: 'David Osezua',
    email: 'david@company.com',
    username: 'davidosezua',
    password: 'GodisGreat2024',
    mobilePhone: '08111112222',
    status: 'Active',
    branch: 'Port Harcourt',
    superUser: false,
    address: '10 Stadium Road, PH',
    roles: 'User',
    profilePicture: 'https://example.com/profiles/david.jpg',
  },
  {
    id: 4,
    fullName: 'Sarah Johnson',
    email: 'sarahj@example.com',
    username: 'sarahj',
    password: 'SarahSecure01!',
    mobilePhone: '08122223333',
    status: 'Active',
    branch: 'Ibadan',
    superUser: false,
    address: '15 Bodija, Ibadan',
    roles: 'Support',
    profilePicture: 'https://example.com/profiles/sarah.jpg',
  },
  {
    id: 5,
    fullName: 'Michael Lee',
    email: 'mikelee@example.com',
    username: 'mikelee',
    password: 'Mike@2023',
    mobilePhone: '08034445566',
    status: 'Inactive',
    branch: 'Kano',
    superUser: true,
    address: '22 Zoo Road, Kano',
    roles: 'Admin',
    profilePicture: 'https://example.com/profiles/mike.jpg',
  },
  {
    id: 6,
    fullName: 'Amina Bello',
    email: 'amina@example.com',
    username: 'aminabello',
    password: 'Amina#Secure',
    mobilePhone: '07056667788',
    status: 'Active',
    branch: 'Kaduna',
    superUser: false,
    address: '5 Independence Way, Kaduna',
    roles: 'User',
    profilePicture: 'https://example.com/profiles/amina.jpg',
  },
  {
    id: 7,
    fullName: 'Peter Obi',
    email: 'obi@example.com',
    username: 'peterobi',
    password: 'ObiVictory2023!',
    mobilePhone: '09012345678',
    status: 'Active',
    branch: 'Enugu',
    superUser: true,
    address: '1 Government House, Enugu',
    roles: 'Admin',
    profilePicture: 'https://example.com/profiles/obi.jpg',
  },
  {
    id: 8,
    fullName: 'Ngozi Nwosu',
    email: 'ngozi@example.com',
    username: 'ngozinw',
    password: 'Nwosu@2023',
    mobilePhone: '07099887766',
    status: 'Inactive',
    branch: 'Owerri',
    superUser: false,
    address: '17 Douglas Road, Owerri',
    roles: 'Support',
    profilePicture: 'https://example.com/profiles/ngozi.jpg',
  },
  {
    id: 9,
    fullName: 'Samuel Eze',
    email: 'samuel@example.com',
    username: 'samuze',
    password: 'SamEZ@secure',
    mobilePhone: '08189998877',
    status: 'Active',
    branch: 'Benin City',
    superUser: false,
    address: '45 Uselu Road, Benin',
    roles: 'User',
    profilePicture: 'https://example.com/profiles/samuel.jpg',
  },
  {
    id: 10,
    fullName: 'Chinyere Okafor',
    email: 'chinyere@example.com',
    username: 'chinyo',
    password: 'Chinyere#123',
    mobilePhone: '08033445566',
    status: 'Inactive',
    branch: 'Aba',
    superUser: true,
    address: '8 Ariaria Market, Aba',
    roles: 'Manager',
    profilePicture: 'https://example.com/profiles/chinyere.jpg',
  },
  {
    id: 11,
    fullName: 'Tunde Bakare',
    email: 'tunde@example.com',
    username: 'tundeb',
    password: 'TundeSecure1!',
    mobilePhone: '07012233445',
    status: 'Active',
    branch: 'Ibadan',
    superUser: false,
    address: '10 Ring Road, Ibadan',
    roles: 'User',
    profilePicture: 'https://example.com/profiles/tunde.jpg',
  },
  {
    id: 12,
    fullName: 'Blessing James',
    email: 'blessing@example.com',
    username: 'blessj',
    password: 'Blessing2024!',
    mobilePhone: '08123450987',
    status: 'Inactive',
    branch: 'Jos',
    superUser: true,
    address: '12 Rayfield, Jos',
    roles: 'Support',
    profilePicture: 'https://example.com/profiles/blessing.jpg',
  },
  {
    id: 13,
    fullName: 'Kehinde Adebayo',
    email: 'kehinde@example.com',
    username: 'kehindea',
    password: 'KehindePass!',
    mobilePhone: '07011223344',
    status: 'Active',
    branch: 'Oshogbo',
    superUser: false,
    address: '19 Gbongan Rd, Osun',
    roles: 'Admin',
    profilePicture: 'https://example.com/profiles/kehinde.jpg',
  },
  {
    id: 14,
    fullName: 'Rachael Itodo',
    email: 'rachael@example.com',
    username: 'rachaelitodo',
    password: 'Rachael@1',
    mobilePhone: '09087654321',
    status: 'Active',
    branch: 'Makurdi',
    superUser: true,
    address: '23 High Level, Makurdi',
    roles: 'Manager',
    profilePicture: 'https://example.com/profiles/rachael.jpg',
  },
  {
    id: 15,
    fullName: 'Yusuf Ahmed',
    email: 'yusuf@example.com',
    username: 'yusufahm',
    password: 'YusufSecure23',
    mobilePhone: '08066778899',
    status: 'Inactive',
    branch: 'Sokoto',
    superUser: false,
    address: '7 Emir Palace Rd, Sokoto',
    roles: 'User',
    profilePicture: 'https://example.com/profiles/yusuf.jpg',
  },
  {
    id: 16,
    fullName: 'Mariam Lawal',
    email: 'mariam@example.com',
    username: 'mariamlawal',
    password: 'Mariam2025!',
    mobilePhone: '08177776655',
    status: 'Active',
    branch: 'Ilorin',
    superUser: true,
    address: '14 Post Office Rd, Ilorin',
    roles: 'Support',
    profilePicture: 'https://example.com/profiles/mariam.jpg',
  },
  {
    id: 17,
    fullName: 'Ifeanyi Kalu',
    email: 'ifeanyi@example.com',
    username: 'ifykalu',
    password: 'Ify#Secure456',
    mobilePhone: '08055443322',
    status: 'Inactive',
    branch: 'Uyo',
    superUser: false,
    address: '34 Oron Road, Uyo',
    roles: 'Admin',
    profilePicture: 'https://example.com/profiles/ifeanyi.jpg',
  },
  {
    id: 18,
    fullName: 'Grace Udoh',
    email: 'grace@example.com',
    username: 'graceudoh',
    password: 'GraceU@safe',
    mobilePhone: '09011225566',
    status: 'Active',
    branch: 'Calabar',
    superUser: false,
    address: '2 Marian Rd, Calabar',
    roles: 'Manager',
    profilePicture: 'https://example.com/profiles/grace.jpg',
  },
  {
    id: 19,
    fullName: 'Tobi Alade',
    email: 'tobi@example.com',
    username: 'tobialade',
    password: 'TobiCool2023',
    mobilePhone: '08099887744',
    status: 'Inactive',
    branch: 'Abeokuta',
    superUser: true,
    address: '13 Panseke Rd, Abeokuta',
    roles: 'Support',
    profilePicture: 'https://example.com/profiles/tobi.jpg',
  },
  {
    id: 20,
    fullName: 'Nkechi Umeh',
    email: 'nkechi@example.com',
    username: 'nkechiu',
    password: 'NkechiStrong@01',
    mobilePhone: '08111223344',
    status: 'Active',
    branch: 'Onitsha',
    superUser: false,
    address: '6 Awka Rd, Onitsha',
    roles: 'User',
    profilePicture: 'https://example.com/profiles/nkechi.jpg',
  },
];
